### ISSUE TITLE
Donate modal z-index at 0

### ISSUE THREAD

**Issue by F-Node-Karlsruhe** [iota-button/iota-button#19]
When opening the donate modal to choose the amount it hides behind other elements. 
The following modal is above the other elements again.

**Comment by adamkundrat** [comment]
Thanks, we will investigate!

**Comment by F-Node-Karlsruhe** [comment]
You can see it here https://blog.f-node.de/author/f-node/
Sorry, I forgot to add that to the initial issue

**Comment by frnfa** [comment]
hi @F-Node-Karlsruhe 
before we fix this issue, there is a workaround that can be done on your side...
you can change "position: sticky" to "position: inherit" within the "author-profile-content" class

let me know if this helped

**Comment by adamkundrat** [comment]
Fix was released into the modal. It should work well on your website even without the workaround.
