### ISSUE TITLE
UI feedback

### ISSUE THREAD

**Issue by Critical94** [iota-button/iota-button#20]
Hi, I thought you might be interested in feedback. I had a few ideas for the modal, maybe one or the other will help :)

- The donation button should have a highlight color that stands out from the other elements. 
- Use the same font-family for the button (it is arial atm)
- Donation amount and donation time in black 
- I'm not a fan of the close button outside the modal, but maybe only my preference 

(Quick and dirty) Example:
![Screenshot_2x](https://user-images.githubusercontent.com/53269239/122941416-a94d9380-d375-11eb-88f8-fe39041af446.jpg)

**Comment by frnfa** [comment]
@Critical94 thanks for this, I agree... I will tweak the modal together with pending mobile view updates
