### ISSUE TITLE
Donation Collection

### ISSUE THREAD

**Issue by adamkundrat** [iota-button/iota-button#7]
Very similar to #1 although the flow will be slightly different:

**Proposed improvements:**
- user selects how much they want to donate (based on suggestions)
- user can see total donated and historical donations 
- improved UI/UX flow

**Ideas**
- provide HTML button they can put on their website, share on socials, etc. with details sourced from tangle.

**Comment by AdamCroply** [comment]
Hi Adam! We're working on a couple of projects where this would be AMAZINGLY useful (including the IOTA wiki) do you have any idea when this may be in the pipeline? The work you are doing is awesome! :)

**Comment by adamkundrat** [comment]
thanks @AdamCroply. Quite busy so I didn't have a chance to continue much on this since I shared this...

I'm happy to talk with @frnfa and maybe we can get this one across. It'll be great to have a quick chat three of us sometime this week?! We could talk about timeline you are after and key use case you want it to support. My handle on discord adam_unchained#5334 and josef is frnfa#0604

**Comment by AdamCroply** [comment]
I've messagedbin discord would be great to have abchat some time.

**Comment by adamkundrat** [comment]
We've had a great chat with @AdamCroply. There seems to be great demand for this. We'll prioritize to finalize this one first so ppl can use it.

**We plan to do:**
- improve over all layout from the button click to the donation
- show historical donations and running balance (promotes user to donate more)
- present user with choices on how much to donate

**IDEAS**
- once Firefly supports messages we can do much more (i.e. messages, certificates, etc.)

I'm hoping we might have this by eow.
